# Configuración del servidor Spring Boot
server:
  port: ${PORT}  # Puerto en el que corre la aplicación (8080 por defecto)

# Configuración de la base de datos y JPA
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/defaultdb}  # URL de la base de datos
    username: ${SPRING_DATASOURCE_USERNAME:root}  # Nombre de usuario de la base de datos
    password: ${SPRING_DATASOURCE_PASSWORD:}  # Contraseña de la base de datos
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}  # Driver de MySQL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SPRING_JPA_SHOW_SQL:true}  # Mostrar las consultas SQL en la consola
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}  # Dialecto de Hibernate para MySQL

# Configuración del truststore para conexiones SSL
javax:
  net:
    ssl:
      trustStore: ${JAVAX_NET_SSL_TRUSTSTORE:classpath:ssl/truststore.jks}  # Ruta al truststore
      trustStorePassword: ${JAVAX_NET_SSL_TRUSTSTOREPASSWORD:changeit}  # Contraseña del truststore