spring:
  datasource:
    url: jdbc:mysql://baskettrainer-db-baskettrainer-db.k.aivencloud.com:27546/defaultdb?ssl-mode=VERIFY_CA&useSSL=true
    username: avnadmin
    password: [AIVEN_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

javax:
  net:
    ssl:
      trustStore: classpath:ssl/truststore.jks
      trustStorePassword: changeit